name: Publish to GHCR
on:
    release:
        types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        - name: Docker meta
          id: meta
          uses: docker/metadata-action@v5
          with:
            images: ghcr.io/JMaynor/yt-dynamic-opml
            tags: |
              type=sha
              type=ref,event=branch,ref=main
        - name: Login to GHCR
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - name: Build container
          uses: docker/build-push-action@v6
          with:
            context: .
            push: true
            tags: |
              ${{ steps.meta.outputs.tags }}
              ghcr.io/jmaynor/yt-dynamic-opml:latest
